using System;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI;

/// <summary>
/// Standard UI control used for check boxes and toggles in the options menu.
/// Features a two-column layout aligning with OptionSlider and OptionDropDown.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class OptionCheckBox : Control
{
    private static readonly StyleBoxFlat HoverStyle = new()
    {
        BackgroundColor = Color.FromHex("#1E2229"),
        BorderColor = Color.FromHex("#D48944"),
        BorderThickness = new Thickness(2, 0, 0, 0),
        ContentMarginLeftOverride = 4,
    };

    private string? _description;

    public event Action<bool>? OnRowToggled;
    public event Action<BaseButton.ButtonToggledEventArgs>? OnToggled;

    public OptionCheckBox()
    {
        RobustXamlLoader.Load(this);

        RowPanel.MouseFilter = MouseFilterMode.Stop;
        NameLabel.MouseFilter = MouseFilterMode.Pass;
        DescriptionLabel.MouseFilter = MouseFilterMode.Pass;

        RowPanel.OnMouseEntered += _ => RowPanel.PanelOverride = HoverStyle;
        RowPanel.OnMouseExited += _ => RowPanel.PanelOverride = null;

        CheckBox.OnToggled += args =>
        {
            OnToggled?.Invoke(args);
            OnRowToggled?.Invoke(args.Pressed);
        };

        RowPanel.OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick && !Disabled)
            {
                // SetClickPressed only flips the visual state, so dispatch the toggle manually.
                CheckBox.SetClickPressed(!CheckBox.Pressed);
                var toggledArgs = new BaseButton.ButtonToggledEventArgs(CheckBox.Pressed, CheckBox, args);
                OnToggled?.Invoke(toggledArgs);
                OnRowToggled?.Invoke(CheckBox.Pressed);
                args.Handle();
            }
        };
    }

    /// <summary>
    /// The text describing what this check box controls.
    /// </summary>
    public string? Title
    {
        get => NameLabel.Text;
        set => NameLabel.Text = value;
    }

    /// <summary>
    /// Tooltip text for the option, displayed when hovering anywhere over the row.
    /// </summary>
    public new string? ToolTip
    {
        get => base.ToolTip;
        set
        {
            base.ToolTip = value;
            NameLabel.ToolTip = value;
            CheckBox.ToolTip = value;
            RowPanel.ToolTip = value;
        }
    }

    /// <summary>
    /// Subtitle/description text for the option, displayed right under the title.
    /// </summary>
    public string? Description
    {
        get => _description ?? ToolTip;
        set
        {
            _description = value;
            DescriptionLabel.Text = value;
            DescriptionLabel.Visible = !string.IsNullOrWhiteSpace(value);
            ToolTip = value;
        }
    }

    /// <summary>
    /// Whether the check box is currently pressed / checked.
    /// </summary>
    public bool Pressed
    {
        get => CheckBox.Pressed;
        set => CheckBox.Pressed = value;
    }

    /// <summary>
    /// Whether user interaction with the check box is disabled.
    /// </summary>
    public bool Disabled
    {
        get => CheckBox.Disabled;
        set => CheckBox.Disabled = value;
    }

    public static implicit operator CheckBox(OptionCheckBox row) => row.CheckBox;
}
