using Content.Client.Options.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI;

/// <summary>
/// Standard UI control used for color sliders in the options menu. Intended for use with <see cref="OptionsTabControlRow"/>.
/// </summary>
/// <seealso cref="OptionsTabControlRow.AddOptionColorSlider"/>
[GenerateTypedNameReferences]
public sealed partial class OptionColorSlider : Control
{
    private static readonly StyleBoxFlat HoverStyle = new()
    {
        BackgroundColor = Color.FromHex("#1E2229"),
        BorderColor = Color.FromHex("#D48944"),
        BorderThickness = new Thickness(2, 0, 0, 0),
        ContentMarginLeftOverride = 4,
    };

    public OptionColorSlider()
    {
        RobustXamlLoader.Load(this);

        RowPanel.MouseFilter = MouseFilterMode.Pass;
        TitleLabel.MouseFilter = MouseFilterMode.Pass;
        ExampleLabel.MouseFilter = MouseFilterMode.Pass;

        RowPanel.OnMouseEntered += _ => RowPanel.PanelOverride = HoverStyle;
        RowPanel.OnMouseExited += _ => RowPanel.PanelOverride = null;
    }
    /// <summary>
    /// The text describing what this slider affects.
    /// </summary>
    public string? Title
    {
        get => TitleLabel.Text;
        set => TitleLabel.Text = value;
    }

    /// <summary>
    /// The example text showing the current color of the slider.
    /// </summary>
    public string? Example
    {
        get => ExampleLabel.Text;
        set => ExampleLabel.Text = value;
    }

    /// <summary>
    /// Tooltip text for the option, displayed when hovering anywhere over the row.
    /// </summary>
    public new string? ToolTip
    {
        get => base.ToolTip;
        set
        {
            base.ToolTip = value;
            TitleLabel.ToolTip = value;
            Slider.ToolTip = value;
        }
    }

    /// <summary>
    /// Tooltip/description text for the option.
    /// </summary>
    public string? Description
    {
        get => ToolTip;
        set => ToolTip = value;
    }
}
