name: Сообщить об ошибке
description: Для ошибок, не связанных с другими шаблонами.
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить этот отчет. Данный шаблон предназначен для любых ошибок, которые не подходят под другие шаблоны.
        По вопросам обратной связи или помощи с запуском заходите на наш [Discord](https://discord.gg/6hZhXhtUv).
  - type: input
    attributes:
      label: В какой версии возникла ошибка?
      description: Версию можно найти, открыв в игре журнал изменений и посмотрев в правый нижний угол окна.
      placeholder: ashfall/aa1337b
    validations:
      required: false
  - type: textarea
    attributes:
      label: Описание
      description: |
        Краткое описание ошибки.
        Если проблема визуальная, приложите скриншот.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Воспроизведение
      description: Перечислите шаги для воспроизведения ошибки.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Дополнительный контекст
      description: Добавьте любую дополнительную информацию об ошибке.
    validations:
      required: false
