name: Сообщить об ошибке маппинга
description: Для ошибок, связанных с картами.
body:
  - type: markdown
    attributes:
      value: |
        Спасибо, что нашли время заполнить этот отчет. Данный шаблон предназначен для ошибок, связанных с маппингом.
        По вопросам обратной связи или помощи с запуском заходите на наш [Discord](https://discord.gg/6hZhXhtUv).
  - type: input
    attributes:
      label: В какой версии возникла ошибка?
      description: Версию можно найти, открыв в игре журнал изменений и посмотрев в правый нижний угол окна.
      placeholder: ashfall/aa1337b
    validations:
      required: false
  - type: input
    attributes:
      label: На какой станции, шаттле или гриде возникла ошибка?
      description: Название станции, шаттла или грида. Если не знаете названия, опишите место.
      placeholder: Bagel
    validations:
      required: true
  - type: textarea
    attributes:
      label: Описание
      description: |
        Краткое описание ошибки.
        Если проблема визуальная, приложите скриншот.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Воспроизведение
      description: Перечислите шаги для воспроизведения ошибки.
      placeholder: |
        1.
        2.
        3.
        ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Дополнительный контекст
      description: Добавьте любую дополнительную информацию об ошибке.
    validations:
      required: false
