blank_issues_enabled: true
contact_links:
  - name: Предложить фичу
    url: https://github.com/orgs/ashfall-ss14/projects/1
    about: Предложения по новым фичам присылайте на доску предложений организации.
