blank_issues_enabled: true
contact_links:
  - name: Предложить фичу
    url: https://discord.gg/HuVyc4SWpB
    about: Предложения по новым фичам присылайте на доску предложений в нашем Discord-сервере.
