using System.Linq;
using System.Numerics;
using Content.Client.Message;
using Content.Shared.Ashfall.CharacterGen;
using Content.Shared.Ashfall.CharacterGen.Lifepath;
using Content.Shared.Ashfall.CharacterGen.Prototypes;
using Content.Shared.Dataset;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Shared.Enums;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;

namespace Content.Client.Ashfall.CharacterGen.UI.Lifepath;

public sealed partial class AshfallLifepathScreen : PanelContainer
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IRobustRandom _random = default!;

    private readonly AshfallCharacterGenSystem _genSystem;
    private readonly AshfallCharacterGenerator _characterGenerator;
    private readonly AshfallPersonGenerator _personGenerator;

    private Button BackButton => this.FindControl<Button>("BackButton");
    private Label StepIndicatorLabel => this.FindControl<Label>("StepIndicatorLabel");
    private ProfileFullBodySpriteView PreviewSprite => this.FindControl<ProfileFullBodySpriteView>("PreviewSprite");
    private Label LiveSpeciesLabel => this.FindControl<Label>("LiveSpeciesLabel");
    private Label LiveVectorLabel => this.FindControl<Label>("LiveVectorLabel");
    private Label LiveFlawLabel => this.FindControl<Label>("LiveFlawLabel");
    private Label LiveLuggageLabel => this.FindControl<Label>("LiveLuggageLabel");

    private Label PromptHeaderLabel => this.FindControl<Label>("PromptHeaderLabel");
    private Label PromptQuestionLabel => this.FindControl<Label>("PromptQuestionLabel");

    private ScrollContainer OptionsScroll => this.FindControl<ScrollContainer>("OptionsScroll");
    private BoxContainer OptionsContainer => this.FindControl<BoxContainer>("OptionsContainer");

    private BoxContainer FinalSummaryContainer => this.FindControl<BoxContainer>("FinalSummaryContainer");
    private Label SummaryTitle => this.FindControl<Label>("SummaryTitle");
    private LineEdit NameInput => this.FindControl<LineEdit>("NameInput");
    private Button RerollNameButton => this.FindControl<Button>("RerollNameButton");
    private OptionButton ExperienceOption => this.FindControl<OptionButton>("ExperienceOption");
    private OptionButton JobOption => this.FindControl<OptionButton>("JobOption");
    private Label SummaryFlawLabel => this.FindControl<Label>("SummaryFlawLabel");
    private Label SummaryLuggageLabel => this.FindControl<Label>("SummaryLuggageLabel");
    private Button ConfirmCandidateButton => this.FindControl<Button>("ConfirmCandidateButton");

    private int _targetSlot;
    private int _currentStep = 1;
    private AshfallLifepathChoices _choices = new();

    private HumanoidCharacterProfile? _currentProfile;

    private readonly List<ProtoId<JobPrototype>> _departmentJobs = new();

    public event Action? BackToLobby;
    public event Action? Finished;

    public AshfallLifepathScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _genSystem = _entMan.System<AshfallCharacterGenSystem>();
        var naming = _entMan.System<NamingSystem>();
        var marking = IoCManager.Resolve<Content.Shared.Humanoid.Markings.MarkingManager>();

        _characterGenerator = new AshfallCharacterGenerator(_prototypes, marking, naming);
        _personGenerator = new AshfallPersonGenerator(_prototypes, _characterGenerator);

        BackButton.OnPressed += _ => BackToLobby?.Invoke();
        RerollNameButton.OnPressed += _ => RerollName();
        ExperienceOption.OnItemSelected += OnExperienceChanged;
        JobOption.OnItemSelected += OnJobSelected;
        ConfirmCandidateButton.OnPressed += _ => ConfirmCandidate();
    }

    public void Start(int slotIndex)
    {
        _targetSlot = slotIndex;
        _choices = new AshfallLifepathChoices { TargetSlotIndex = slotIndex };
        _currentStep = 1;
        _currentProfile = null;

        LiveSpeciesLabel.Text = string.Empty;
        LiveVectorLabel.Text = string.Empty;
        LiveFlawLabel.Text = string.Empty;
        LiveLuggageLabel.Text = string.Empty;

        PreviewSprite.ClearPreview();
        LoadStep(1);
    }

    private void LoadStep(int step)
    {
        _currentStep = step;

        switch (step)
        {
            case 1:
                StepIndicatorLabel.Text = Loc.GetString("ashfall-lifepath-header-step1");
                PromptHeaderLabel.Text = Loc.GetString("ashfall-lifepath-header-step1");
                PromptQuestionLabel.Text = Loc.GetString("ashfall-lifepath-prompt-step1");
                break;
            case 2:
                StepIndicatorLabel.Text = Loc.GetString("ashfall-lifepath-header-step2");
                PromptHeaderLabel.Text = Loc.GetString("ashfall-lifepath-header-step2");
                PromptQuestionLabel.Text = Loc.GetString("ashfall-lifepath-prompt-step2");
                break;
            case 3:
                StepIndicatorLabel.Text = Loc.GetString("ashfall-lifepath-header-step3");
                PromptHeaderLabel.Text = Loc.GetString("ashfall-lifepath-header-step3");
                PromptQuestionLabel.Text = Loc.GetString("ashfall-lifepath-prompt-step3");
                break;
            case 4:
                StepIndicatorLabel.Text = Loc.GetString("ashfall-lifepath-header-step4");
                PromptHeaderLabel.Text = Loc.GetString("ashfall-lifepath-header-step4");
                PromptQuestionLabel.Text = Loc.GetString("ashfall-lifepath-prompt-step4");
                break;
            case 5:
                StepIndicatorLabel.Text = Loc.GetString("ashfall-lifepath-header-step5");
                PromptHeaderLabel.Text = Loc.GetString("ashfall-lifepath-header-step5");
                PromptQuestionLabel.Text = Loc.GetString("ashfall-lifepath-prompt-step5");
                break;
        }

        if (step <= 4)
        {
            OptionsScroll.Visible = true;
            FinalSummaryContainer.Visible = false;
            PopulateOptions(step);
        }
        else
        {
            OptionsScroll.Visible = false;
            FinalSummaryContainer.Visible = true;
            PopulateFinalSummary();
        }
    }

    private void PopulateOptions(int step)
    {
        OptionsContainer.RemoveAllChildren();

        var options = _prototypes.EnumeratePrototypes<AshfallLifepathOptionPrototype>()
            .Where(o => o.Step == step)
            .ToList();

        foreach (var opt in options)
        {
            var card = CreateOptionCard(opt);
            OptionsContainer.AddChild(card);
        }
    }

    private Control CreateOptionCard(AshfallLifepathOptionPrototype opt)
    {
        var panel = new PanelContainer
        {
            HorizontalExpand = true,
            MinHeight = 68,
        };

        var idleBorder = Color.FromHex("#2C2E33");
        var hoverBorder = opt.IndicatorColor;

        var boxStyle = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#151618"),
            BorderColor = idleBorder,
            BorderThickness = new Thickness(1),
        };
        panel.PanelOverride = boxStyle;

        var button = new Button
        {
            StyleClasses = { "ButtonOpenBoth" },
            HorizontalExpand = true,
            VerticalExpand = true,
        };

        button.OnPressed += _ => SelectOption(opt);
        button.OnMouseEntered += _ =>
        {
            boxStyle.BorderColor = hoverBorder;
            boxStyle.BackgroundColor = Color.FromHex("#201E1B");
        };
        button.OnMouseExited += _ =>
        {
            boxStyle.BorderColor = idleBorder;
            boxStyle.BackgroundColor = Color.FromHex("#151618");
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(10, 8),
            SeparationOverride = 12,
            HorizontalExpand = true,
        };

        // Left color indicator bar
        var bar = new PanelContainer
        {
            SetSize = new Vector2(5, 50),
            VerticalAlignment = VAlignment.Center,
            PanelOverride = new StyleBoxFlat { BackgroundColor = opt.IndicatorColor },
        };
        row.AddChild(bar);

        var col = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 4,
            HorizontalExpand = true,
        };

        var titleLabel = new Label
        {
            Text = Loc.GetString(opt.Title),
            FontColorOverride = Color.FromHex("#E6E8E6"),
            StyleClasses = { "FancyWindowTitle" },
        };
        col.AddChild(titleLabel);

        var descLabel = new Label
        {
            Text = Loc.GetString(opt.Description),
            FontColorOverride = Color.FromHex("#878C87"),
            ClipText = true,
        };
        col.AddChild(descLabel);

        row.AddChild(col);
        button.AddChild(row);
        panel.AddChild(button);

        return panel;
    }

    private void SelectOption(AshfallLifepathOptionPrototype opt)
    {
        switch (opt.Step)
        {
            case 1:
                _choices.Step1Origin = opt.ID;
                LiveSpeciesLabel.Text = Loc.GetString(opt.Title);
                UpdateSpriteStep1(opt);
                LoadStep(2);
                break;

            case 2:
                _choices.Step2Vector = opt.ID;
                LiveVectorLabel.Text = Loc.GetString(opt.Title);
                UpdateSpriteStep2(opt);
                LoadStep(3);
                break;

            case 3:
                _choices.Step3Flaw = opt.ID;
                LiveFlawLabel.Text = Loc.GetString(opt.Title);
                LoadStep(4);
                break;

            case 4:
                _choices.Step4Luggage = opt.ID;
                LiveLuggageLabel.Text = Loc.GetString(opt.Title);
                LoadStep(5);
                break;
        }
    }

    private void UpdateSpriteStep1(AshfallLifepathOptionPrototype opt)
    {
        var speciesId = opt.Species ?? "Human";
        var species = _prototypes.Index(speciesId);

        CharacterGenConstraintsPrototype constraints;
        if (_prototypes.TryIndex<CharacterGenConstraintsPrototype>($"{species.ID}DefaultConstraints", out var found))
            constraints = found;
        else
        {
            ProtoId<CharacterGenConstraintsPrototype> fallbackId = "HumanDefaultConstraints";
            constraints = _prototypes.Index(fallbackId);
        }

        AshfallCulturePrototype? culture = null;
        if (opt.Culture is { } cId && _prototypes.TryIndex(cId, out var cult))
            culture = cult;

        var sex = _random.Pick(species.Sexes);
        var gender = sex switch
        {
            Sex.Female => Gender.Female,
            Sex.Male => Gender.Male,
            _ => Gender.Epicene
        };

        var age = 30;
        var (appearance, _) = _characterGenerator.GenerateAppearance(constraints, species, sex, age, _random, culture);
        var name = culture != null
            ? _random.Pick(_prototypes.Index<DatasetPrototype>(gender == Gender.Female ? culture.FirstNamesFemale : culture.FirstNamesMale).Values) + " " +
              _random.Pick(_prototypes.Index<DatasetPrototype>(culture.LastNames).Values)
            : "Кандидат";

        _currentProfile = _characterGenerator.BuildProfile(name, species, sex, gender, age, appearance, _random);
        PreviewSprite.LoadPreview(_currentProfile, null, showClothes: false);
    }

    private void UpdateSpriteStep2(AshfallLifepathOptionPrototype opt)
    {
        if (_currentProfile == null)
            return;

        if (opt.PreviewJob is { } jobId && _prototypes.TryIndex(jobId, out JobPrototype? job))
        {
            PreviewSprite.LoadPreview(_currentProfile, job, showClothes: true);
        }
    }

    private void PopulateFinalSummary()
    {
        SummaryTitle.Text = Loc.GetString("ashfall-lifepath-summary-title", ("slot", _targetSlot + 1));
        ConfirmCandidateButton.Text = Loc.GetString("ashfall-lifepath-confirm-button", ("slot", _targetSlot + 1));

        if (_currentProfile != null)
            NameInput.Text = _currentProfile.Name;

        // Experience tiers
        ExperienceOption.Clear();
        ExperienceOption.AddItem(Loc.GetString("ashfall-lifepath-exp-junior"), 0);
        ExperienceOption.AddItem(Loc.GetString("ashfall-lifepath-exp-standard"), 1);
        ExperienceOption.AddItem(Loc.GetString("ashfall-lifepath-exp-veteran"), 2);
        ExperienceOption.SelectId(_choices.ExperienceTier);

        // Populate jobs strictly from the chosen domain
        _prototypes.TryIndex(_choices.Step2Vector, out var step2Opt);
        var domain = step2Opt?.Domain ?? "Engineering";

        _departmentJobs.Clear();
        JobOption.Clear();

        var careerRoles = _prototypes.EnumeratePrototypes<AshfallCareerRolePrototype>()
            .Where(r => r.Domain == domain)
            .ToList();

        // Also check actual playable jobs matching domain
        var allJobs = _prototypes.EnumeratePrototypes<JobPrototype>()
            .Where(j => j.SetPreference)
            .ToList();

        var matchingJobs = allJobs
            .Where(j => IsJobInDomain(j, domain))
            .ToList();

        if (matchingJobs.Count == 0 && step2Opt?.PreviewJob is { } prevJob && _prototypes.TryIndex(prevJob, out JobPrototype? pj))
        {
            matchingJobs.Add(pj);
        }

        for (var i = 0; i < matchingJobs.Count; i++)
        {
            var job = matchingJobs[i];
            _departmentJobs.Add(job.ID);
            JobOption.AddItem(Loc.GetString(job.Name), i);
        }

        if (_departmentJobs.Count > 0)
        {
            JobOption.SelectId(0);
            _choices.SelectedJob = _departmentJobs[0];
            if (_currentProfile != null && _prototypes.TryIndex(_choices.SelectedJob, out JobPrototype? selectedJobProto))
            {
                PreviewSprite.LoadPreview(_currentProfile, selectedJobProto, showClothes: true);
            }
        }

        // Flaw & luggage summary quotes
        if (_prototypes.TryIndex(_choices.Step3Flaw, out var flawOpt))
        {
            SummaryFlawLabel.Text = $"{Loc.GetString("ashfall-lifepath-header-step3")}: {Loc.GetString(flawOpt.Title)} — {Loc.GetString(flawOpt.Description)}";
        }

        if (_prototypes.TryIndex(_choices.Step4Luggage, out var lugOpt))
        {
            SummaryLuggageLabel.Text = $"{Loc.GetString("ashfall-lifepath-header-step4")}: {Loc.GetString(lugOpt.Title)} — {Loc.GetString(lugOpt.Description)}";
        }
    }

    private static bool IsJobInDomain(JobPrototype job, string domain)
    {
        var id = job.ID.ToLowerInvariant();
        return domain switch
        {
            "Engineering" => id.Contains("engineer") || id.Contains("atmos") || id.Contains("mechanic") || id.Contains("technical"),
            "Medical" => id.Contains("medic") || id.Contains("doctor") || id.Contains("chemist") || id.Contains("paramedic") || id.Contains("virolog"),
            "Security" => id.Contains("security") || id.Contains("officer") || id.Contains("detective") || id.Contains("warden") || id.Contains("cadet"),
            "Service" => id.Contains("janitor") || id.Contains("bartender") || id.Contains("chef") || id.Contains("cook") || id.Contains("botanist") || id.Contains("clown") || id.Contains("mime") || id.Contains("passenger"),
            _ => true,
        };
    }

    private void OnExperienceChanged(OptionButton.ItemSelectedEventArgs args)
    {
        ExperienceOption.SelectId(args.Id);
        _choices.ExperienceTier = args.Id;
    }

    private void OnJobSelected(OptionButton.ItemSelectedEventArgs args)
    {
        JobOption.SelectId(args.Id);
        if (args.Id >= 0 && args.Id < _departmentJobs.Count)
        {
            _choices.SelectedJob = _departmentJobs[args.Id];
            if (_currentProfile != null && _prototypes.TryIndex(_choices.SelectedJob, out JobPrototype? jobProto))
            {
                PreviewSprite.LoadPreview(_currentProfile, jobProto, showClothes: true);
            }
        }
    }

    private void RerollName()
    {
        if (_currentProfile == null)
            return;

        if (_prototypes.TryIndex(_choices.Step1Origin, out var originOpt) &&
            originOpt.Culture is { } cId &&
            _prototypes.TryIndex(cId, out AshfallCulturePrototype? culture))
        {
            var firstDataset = _prototypes.Index<DatasetPrototype>(
                _currentProfile.Gender == Gender.Female ? culture.FirstNamesFemale : culture.FirstNamesMale);
            var lastDataset = _prototypes.Index<DatasetPrototype>(culture.LastNames);

            var first = _random.Pick(firstDataset.Values);
            var last = _random.Pick(lastDataset.Values);
            NameInput.Text = $"{first} {last}";
        }
    }

    private void ConfirmCandidate()
    {
        _choices.CustomName = NameInput.Text;
        _choices.TargetSlotIndex = _targetSlot;

        _genSystem.SubmitLifepath(_choices);
        Finished?.Invoke();
    }
}
