using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Ashfall.Client.Stylesheets;
using Content.Shared.Ashfall.CharacterGen;
using Content.Shared.Ashfall.CharacterGen.Lifepath;
using Content.Shared.Ashfall.CharacterGen.Prototypes;
using Content.Shared.Dataset;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Shared.Enums;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Timing;

namespace Content.Client.Ashfall.CharacterGen.UI.Lifepath;

public sealed partial class AshfallLifepathScreen : PanelContainer
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IRobustRandom _random = default!;

    private const int TotalSteps = 5;
    private const float StaggerDelay = 0.07f;
    private const float StaggerDuration = 0.22f;
    private const float CollapsedAlpha = 0.35f;
    private const float RevealDuration = 0.25f;

    private readonly AshfallCharacterGenSystem _genSystem;
    private readonly AshfallCharacterGenerator _characterGenerator;
    private readonly AshfallPersonGenerator _personGenerator;

    private Button BackButton => this.FindControl<Button>("BackButton");
    private BoxContainer ProgressRail => this.FindControl<BoxContainer>("ProgressRail");
    private Label StepCounterLabel => this.FindControl<Label>("StepCounterLabel");
    private PanelContainer SpriteFrame => this.FindControl<PanelContainer>("SpriteFrame");
    private ProfilePortraitSpriteView PreviewSprite => this.FindControl<ProfilePortraitSpriteView>("PreviewSprite");

    private Label CharacterNameLabel => this.FindControl<Label>("CharacterNameLabel");
    private Label CharacterBioLabel => this.FindControl<Label>("CharacterBioLabel");
    private Label CharacterJobTag => this.FindControl<Label>("CharacterJobTag");
    private Button MaleSexButton => this.FindControl<Button>("MaleSexButton");
    private Button FemaleSexButton => this.FindControl<Button>("FemaleSexButton");
    private BoxContainer ChronicleContainer => this.FindControl<BoxContainer>("ChronicleContainer");

    private Label PromptQuestionLabel => this.FindControl<Label>("PromptQuestionLabel");

    private BoxContainer ContentColumn => this.FindControl<BoxContainer>("ContentColumn");
    private BoxContainer OptionsContainer => this.FindControl<BoxContainer>("OptionsContainer");

    private BoxContainer DossierContainer => this.FindControl<BoxContainer>("DossierContainer");
    private BoxContainer DossierSections => this.FindControl<BoxContainer>("DossierSections");
    private Button RerollNameButton => this.FindControl<Button>("RerollNameButton");
    private OptionButton ExperienceOption => this.FindControl<OptionButton>("ExperienceOption");
    private OptionButton JobOption => this.FindControl<OptionButton>("JobOption");
    private Button ConfirmCandidateButton => this.FindControl<Button>("ConfirmCandidateButton");

    private int _targetSlot;
    private int _currentStep = 1;
    private AshfallLifepathChoices _choices = new();

    private HumanoidCharacterProfile? _currentProfile;
    private string _candidateName = string.Empty;
    private Sex _selectedSex = Sex.Male;
    private AshfallCulturePrototype? _currentCulture;
    private AshfallLifepathOptionPrototype? _step1Option;
    private AshfallLifepathOptionPrototype? _step2Option;

    private readonly List<ProtoId<JobPrototype>> _departmentJobs = new();

    private readonly PanelContainer[] _railSegments = new PanelContainer[TotalSteps];

    private float _staggerTime;
    private readonly List<(Control Card, float Delay)> _staggerCards = new();

    private float _contentFadeTime;
    private bool _contentFading;

    // Accordion state: only titles are visible at first; one click opens the row
    // (description drops in, the rest dim), a second click confirms the choice.
    private sealed record OptionRow(ContainerButton Button, Label Title, Label Desc, PanelContainer Bar);

    private readonly List<OptionRow> _optionRows = new();
    private int _expandedRow = -1;
    private float _revealTime;
    private readonly List<(Control Control, float Delay)> _revealing = new();

    // Slow mystic sway: the portrait drifts, the role bars breathe out of phase.
    private float _swayTime;

    public event Action? BackToLobby;
    public event Action? Finished;

    public AshfallLifepathScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _genSystem = _entMan.System<AshfallCharacterGenSystem>();
        var naming = _entMan.System<NamingSystem>();
        var marking = IoCManager.Resolve<Content.Shared.Humanoid.Markings.MarkingManager>();

        _characterGenerator = new AshfallCharacterGenerator(_prototypes, marking, naming);
        _personGenerator = new AshfallPersonGenerator(_prototypes, _characterGenerator);

        BackButton.OnPressed += _ => BackToLobby?.Invoke();
        RerollNameButton.OnPressed += _ => RerollName();
        MaleSexButton.OnPressed += _ => SetSex(Sex.Male);
        FemaleSexButton.OnPressed += _ => SetSex(Sex.Female);
        ExperienceOption.OnItemSelected += OnExperienceChanged;
        JobOption.OnItemSelected += OnJobSelected;
        ConfirmCandidateButton.OnPressed += _ => ConfirmCandidate();

        PreviewSprite.PortraitFraction = 0.45f;
        PreviewSprite.PortraitScale = 1.35f;
        PreviewSprite.VerticalOffset = -15f;

        BuildProgressRail();
    }

    public void Start(int slotIndex)
    {
        _targetSlot = slotIndex;
        _choices = new AshfallLifepathChoices { TargetSlotIndex = slotIndex };
        _currentStep = 1;
        _currentProfile = null;
        _candidateName = string.Empty;
        _step1Option = null;
        _step2Option = null;
        _currentCulture = null;
        _selectedSex = _random.Prob(0.5f) ? Sex.Male : Sex.Female;

        MaleSexButton.Visible = false;
        FemaleSexButton.Visible = false;

        CharacterNameLabel.Text = string.Empty;
        CharacterBioLabel.Text = Loc.GetString("ashfall-lifepath-default-candidate-name");
        CharacterJobTag.Text = string.Empty;
        RerollNameButton.Visible = false;
        ChronicleContainer.RemoveAllChildren();

        SpriteFrame.Visible = false;
        PreviewSprite.ClearPreview();
        LoadStep(1);
    }

    private void BuildProgressRail()
    {
        for (var i = 0; i < TotalSteps; i++)
        {
            var segment = new PanelContainer { SetSize = new Vector2(26, 3) };
            segment.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#232528") };
            ProgressRail.AddChild(segment);
            _railSegments[i] = segment;
        }
    }

    private void UpdateProgressRail()
    {
        for (var i = 0; i < TotalSteps; i++)
        {
            var color = i + 1 < _currentStep
                ? Color.FromHex("#8A5C33")
                : i + 1 == _currentStep
                    ? AshfallStylesheet.PrimaryAmber
                    : Color.FromHex("#232528");
            ((StyleBoxFlat) _railSegments[i].PanelOverride!).BackgroundColor = color;
        }

        StepCounterLabel.Text = Loc.GetString("ashfall-lifepath-step-counter", ("step", _currentStep), ("total", TotalSteps));
    }

    private void LoadStep(int step)
    {
        _currentStep = step;
        UpdateProgressRail();

        PromptQuestionLabel.Text = Loc.GetString($"ashfall-lifepath-prompt-step{step}");

        if (step <= 4)
        {
            OptionsContainer.Visible = true;
            DossierContainer.Visible = false;
            PopulateOptions(step);
        }
        else
        {
            OptionsContainer.Visible = false;
            DossierContainer.Visible = true;
            PopulateDossier();
        }

        // Page-level fade on every step change, like a site navigating between sections.
        _contentFadeTime = 0f;
        ContentColumn.Modulate = Color.FromHex("#FFFFFF00");
        _contentFading = true;
    }

    private void PopulateOptions(int step)
    {
        OptionsContainer.RemoveAllChildren();
        _optionRows.Clear();
        _staggerCards.Clear();
        _staggerTime = 0f;
        _expandedRow = -1;
        _revealing.Clear();

        var options = _prototypes.EnumeratePrototypes<AshfallLifepathOptionPrototype>()
            .Where(o => o.Step == step)
            .ToList();
        _random.Shuffle(options);

        // Larger pools than the offered set: reruns rarely share a full sheet.
        options = options.Take(4).ToList();

        for (var i = 0; i < options.Count; i++)
        {
            var row = CreateOptionRow(i + 1, options[i]);
            row.Button.Modulate = Color.FromHex("#FFFFFF00");
            _staggerCards.Add((row.Button, i * StaggerDelay));
            _optionRows.Add(row);
            OptionsContainer.AddChild(row.Button);
        }
    }

    private OptionRow CreateOptionRow(int index, AshfallLifepathOptionPrototype opt)
    {
        var button = new ContainerButton
        {
            StyleClasses = { ContainerButton.StyleClassButton, AshfallDossierSheetlet.OptionCardClass },
            HorizontalExpand = true,
        };

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 16,
            HorizontalExpand = true,
        };

        // Role-colored vertical accent bar
        var bar = new PanelContainer
        {
            SetSize = new Vector2(3, 24),
            VerticalAlignment = VAlignment.Top,
            Margin = new Thickness(0, 3, 0, 0),
            PanelOverride = new StyleBoxFlat { BackgroundColor = opt.IndicatorColor },
        };
        row.AddChild(bar);

        var col = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };

        var titleLabel = new Label
        {
            Text = Loc.GetString(opt.Title),
            StyleClasses = { AshfallDossierSheetlet.OptionTitleClass },
        };
        col.AddChild(titleLabel);

        // Hidden until the row is opened; then it drops in like a memory fragment.
        var descLabel = new Label
        {
            Text = Loc.GetString(opt.Description),
            StyleClasses = { AshfallDossierSheetlet.SerifClass },
            Visible = false,
            Margin = new Thickness(0, 2, 0, 0),
        };
        col.AddChild(descLabel);

        row.AddChild(col);
        button.AddChild(row);

        var captured = opt;
        button.OnPressed += _ => OnRowPressed(index - 1, captured);

        return new OptionRow(button, titleLabel, descLabel, bar);
    }

    private void OnRowPressed(int index, AshfallLifepathOptionPrototype opt)
    {
        if (_expandedRow != index)
        {
            ExpandRow(index);
            return;
        }

        // Second press on the open row confirms the choice.
        SelectOption(opt);
    }

    private void ExpandRow(int index)
    {
        _expandedRow = index;
        _revealTime = 0f;
        _revealing.Clear();

        for (var i = 0; i < _optionRows.Count; i++)
        {
            var row = _optionRows[i];
            var expanded = i == index;

            if (expanded && !row.Desc.Visible)
            {
                row.Desc.Visible = true;
                row.Desc.Modulate = Color.FromHex("#FFFFFF00");
                _revealing.Add((row.Desc, 0f));
            }
            else if (!expanded)
            {
                row.Desc.Visible = false;
            }
        }
    }

    private void SelectOption(AshfallLifepathOptionPrototype opt)
    {
        switch (opt.Step)
        {
            case 1:
                _choices.Step1Origin = opt.ID;
                UpdateSpriteStep1(opt);
                AddChronicleEntry("ashfall-lifepath-ledger-origin", opt);
                LoadStep(2);
                break;

            case 2:
                _choices.Step2Vector = opt.ID;
                UpdateSpriteStep2(opt);
                AddChronicleEntry("ashfall-lifepath-ledger-vector", opt);
                LoadStep(3);
                break;

            case 3:
                _choices.Step3Flaw = opt.ID;
                AddChronicleEntry("ashfall-lifepath-ledger-flaw", opt);
                LoadStep(4);
                break;

            case 4:
                _choices.Step4Luggage = opt.ID;
                AddChronicleEntry("ashfall-lifepath-ledger-luggage", opt);
                LoadStep(5);
                break;
        }
    }

    private void AddChronicleEntry(string stepKeyLoc, AshfallLifepathOptionPrototype opt)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 10,
            HorizontalExpand = true,
        };

        var bar = new PanelContainer
        {
            SetSize = new Vector2(3, 18),
            VerticalAlignment = VAlignment.Center,
            PanelOverride = new StyleBoxFlat { BackgroundColor = opt.IndicatorColor },
        };
        row.AddChild(bar);

        var col = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 1,
            HorizontalExpand = true,
        };

        var stepLabel = new Label
        {
            Text = Loc.GetString(stepKeyLoc),
            StyleClasses = { AshfallDossierSheetlet.LedgerStepClass },
        };
        col.AddChild(stepLabel);

        var titleLabel = new Label
        {
            Text = Loc.GetString(opt.Title),
            StyleClasses = { AshfallDossierSheetlet.LedgerValueClass },
            ClipText = true,
        };
        col.AddChild(titleLabel);

        row.AddChild(col);
        ChronicleContainer.AddChild(row);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _swayTime += args.DeltaSeconds;

        if (_contentFading)
        {
            _contentFadeTime += args.DeltaSeconds;
            var fade = Math.Clamp(_contentFadeTime / 0.3f, 0f, 1f);
            var eased = 1f - MathF.Pow(1f - fade, 3);
            ContentColumn.Modulate = new Color(1f, 1f, 1f, eased);
            if (fade >= 1f)
            {
                ContentColumn.Modulate = Color.White;
                _contentFading = false;
            }
        }

        // Entry stagger for option rows.
        var staggering = _staggerCards.Count > 0;
        if (staggering)
        {
            _staggerTime += args.DeltaSeconds;

            for (var i = _staggerCards.Count - 1; i >= 0; i--)
            {
                var (card, delay) = _staggerCards[i];
                if (_staggerTime < delay)
                    continue;

                var progress = Math.Clamp((_staggerTime - delay) / StaggerDuration, 0f, 1f);
                var easedCard = 1f - MathF.Pow(1f - progress, 3);
                card.Modulate = new Color(1f, 1f, 1f, easedCard);

                if (progress >= 1f)
                {
                    card.Modulate = Color.White;
                    _staggerCards.RemoveAt(i);
                }
            }
        }

        // Dropdown reveal of the expanded description.
        if (_revealing.Count > 0)
        {
            _revealTime += args.DeltaSeconds;

            for (var i = _revealing.Count - 1; i >= 0; i--)
            {
                var (control, delay) = _revealing[i];
                if (_revealTime < delay)
                    continue;

                var progress = Math.Clamp((_revealTime - delay) / RevealDuration, 0f, 1f);
                var easedReveal = 1f - MathF.Pow(1f - progress, 3);
                control.Modulate = new Color(1f, 1f, 1f, easedReveal);

                if (progress >= 1f)
                {
                    control.Modulate = Color.White;
                    _revealing.RemoveAt(i);
                }
            }
        }

        // Accordion dimming: unopened rows fade back so the open one owns the screen.
        if (!staggering)
        {
            for (var i = 0; i < _optionRows.Count; i++)
            {
                var row = _optionRows[i];
                var target = _expandedRow < 0 || _expandedRow == i ? 1f : CollapsedAlpha;
                var alpha = MathHelper.Lerp(row.Button.Modulate.A, target, Math.Clamp(args.DeltaSeconds * 10f, 0f, 1f));
                row.Button.Modulate = new Color(1f, 1f, 1f, alpha);
            }
        }

        // Mystic sway: the portrait drifts on a slow sine, role bars breathe out of phase.
        if (SpriteFrame.Visible)
        {
            var bob = MathF.Sin(_swayTime * 1.4f) * 2.5f;
            PreviewSprite.Margin = new Thickness(12, 12 + bob, 12, 12);
        }

        for (var i = 0; i < _optionRows.Count; i++)
        {
            var breath = 0.72f + 0.28f * (0.5f + 0.5f * MathF.Sin(_swayTime * 1.8f + i * 1.1f));
            _optionRows[i].Bar.Modulate = new Color(1f, 1f, 1f, breath);
        }
    }

    private void SetSex(Sex sex)
    {
        if (_selectedSex == sex)
            return;

        _selectedSex = sex;
        UpdateSexButtons();
        if (_step1Option != null)
        {
            RegenerateCandidateIdentity();
        }
    }

    private void UpdateSexButtons()
    {
        MaleSexButton.Modulate = _selectedSex == Sex.Male ? Color.FromHex("#E69C3C") : Color.FromHex("#707882");
        FemaleSexButton.Modulate = _selectedSex == Sex.Female ? Color.FromHex("#E69C3C") : Color.FromHex("#707882");
    }

    private void RegenerateCandidateIdentity()
    {
        if (_step1Option == null)
            return;

        var speciesId = _step1Option.Species ?? "Human";
        var species = _prototypes.Index(speciesId);

        CharacterGenConstraintsPrototype constraints;
        if (_prototypes.TryIndex<CharacterGenConstraintsPrototype>($"{species.ID}DefaultConstraints", out var found))
            constraints = found;
        else
        {
            ProtoId<CharacterGenConstraintsPrototype> fallbackId = "HumanDefaultConstraints";
            constraints = _prototypes.Index(fallbackId);
        }

        var gender = _selectedSex switch
        {
            Sex.Female => Gender.Female,
            Sex.Male => Gender.Male,
            _ => Gender.Epicene
        };

        var age = 30;
        var (appearance, _) = _characterGenerator.GenerateAppearance(constraints, species, _selectedSex, age, _random, _currentCulture);
        var name = _currentCulture != null
            ? _random.Pick(_prototypes.Index<DatasetPrototype>(gender == Gender.Female ? _currentCulture.FirstNamesFemale : _currentCulture.FirstNamesMale).Values) + " " +
              _random.Pick(_prototypes.Index<DatasetPrototype>(_currentCulture.LastNames).Values)
            : Loc.GetString("ashfall-lifepath-default-candidate-name");

        _currentProfile = _characterGenerator.BuildProfile(name, species, _selectedSex, gender, age, appearance, _random);
        _candidateName = name;
        CharacterNameLabel.Text = _candidateName;

        var speciesName = _prototypes.TryIndex<SpeciesPrototype>(_currentProfile.Species, out var sp)
            ? Loc.GetString(sp.Name)
            : string.Empty;
        var cultureName = _currentCulture != null ? Loc.GetString(_currentCulture.Label) : string.Empty;
        CharacterBioLabel.Text = string.IsNullOrEmpty(cultureName) ? speciesName : $"{speciesName} • {cultureName}";

        if (_step2Option != null && _step2Option.PreviewJob is { } jobId && _prototypes.TryIndex(jobId, out JobPrototype? job))
            PreviewSprite.LoadPreview(_currentProfile, job, showClothes: true);
        else
            PreviewSprite.LoadPreview(_currentProfile, null, showClothes: false);
    }

    private void UpdateSpriteStep1(AshfallLifepathOptionPrototype opt)
    {
        _step1Option = opt;
        if (opt.Culture is { } cId && _prototypes.TryIndex(cId, out var cult))
            _currentCulture = cult;
        else
            _currentCulture = null;

        MaleSexButton.Visible = true;
        FemaleSexButton.Visible = true;
        UpdateSexButtons();
        RegenerateCandidateIdentity();
        RerollNameButton.Visible = true;
        SpriteFrame.Visible = true;
    }

    private void UpdateSpriteStep2(AshfallLifepathOptionPrototype opt)
    {
        _step2Option = opt;
        if (_currentProfile == null)
            return;

        if (opt.PreviewJob is { } jobId && _prototypes.TryIndex(jobId, out JobPrototype? job))
        {
            PreviewSprite.LoadPreview(_currentProfile, job, showClothes: true);
        }
    }

    private void PopulateDossier()
    {
        ConfirmCandidateButton.Text = Loc.GetString("ashfall-lifepath-confirm-button", ("slot", _targetSlot + 1));

        // Lifepath sections: each chapter as a record with its own accent color.
        DossierSections.RemoveAllChildren();
        AddDossierSection("ashfall-lifepath-ledger-origin", _choices.Step1Origin, null);
        AddDossierSection("ashfall-lifepath-ledger-vector", _choices.Step2Vector, null);
        AddDossierSection("ashfall-lifepath-ledger-flaw", _choices.Step3Flaw, "ashfall-lifepath-flaw-weakness");
        AddDossierSection("ashfall-lifepath-ledger-luggage", _choices.Step4Luggage, null);

        // Experience tiers
        ExperienceOption.Clear();
        ExperienceOption.AddItem(Loc.GetString("ashfall-lifepath-exp-junior"), 0);
        ExperienceOption.AddItem(Loc.GetString("ashfall-lifepath-exp-standard"), 1);
        ExperienceOption.AddItem(Loc.GetString("ashfall-lifepath-exp-veteran"), 2);
        ExperienceOption.SelectId(_choices.ExperienceTier);

        // Populate jobs strictly from the chosen domain
        _prototypes.TryIndex(_choices.Step2Vector, out var step2Opt);
        var domain = step2Opt?.Domain ?? "Engineering";

        _departmentJobs.Clear();
        JobOption.Clear();

        var allJobs = _prototypes.EnumeratePrototypes<JobPrototype>()
            .Where(j => j.SetPreference)
            .ToList();

        var matchingJobs = allJobs
            .Where(j => IsJobInDomain(j, domain))
            .ToList();

        if (matchingJobs.Count == 0 && step2Opt?.PreviewJob is { } prevJob && _prototypes.TryIndex(prevJob, out JobPrototype? pj))
        {
            matchingJobs.Add(pj);
        }

        for (var i = 0; i < matchingJobs.Count; i++)
        {
            var job = matchingJobs[i];
            _departmentJobs.Add(job.ID);
            JobOption.AddItem(Loc.GetString(job.Name), i);
        }

        if (_departmentJobs.Count > 0)
        {
            JobOption.SelectId(0);
            _choices.SelectedJob = _departmentJobs[0];
        }

        RefreshDossierIdentity();
    }

    private void AddDossierSection(string keyLoc, ProtoId<AshfallLifepathOptionPrototype> optionId, string? weaknessKeyLoc)
    {
        if (!_prototypes.TryIndex(optionId, out var opt))
            return;

        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 12,
            HorizontalExpand = true,
        };

        var bar = new PanelContainer
        {
            SetSize = new Vector2(3, 40),
            PanelOverride = new StyleBoxFlat { BackgroundColor = opt.IndicatorColor },
        };
        row.AddChild(bar);

        var col = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 3,
            HorizontalExpand = true,
        };

        var keyLabel = new Label
        {
            Text = Loc.GetString(keyLoc),
            StyleClasses = { AshfallDossierSheetlet.LabelClass },
        };
        col.AddChild(keyLabel);

        var titleLabel = new Label
        {
            Text = Loc.GetString(opt.Title),
            StyleClasses = { AshfallDossierSheetlet.OptionTitleClass },
        };
        col.AddChild(titleLabel);

        var descLabel = new Label
        {
            Text = Loc.GetString(opt.Description),
            StyleClasses = { AshfallDossierSheetlet.SerifClass },
        };
        col.AddChild(descLabel);

        // The chosen flaw surfaces its concrete weakness; the trait is visible in the dossier.
        if (weaknessKeyLoc != null && opt.StressWeaknessLoc is { } weaknessLoc)
        {
            var weaknessLabel = new Label
            {
                Text = $"{Loc.GetString(weaknessKeyLoc)}: {Loc.GetString(weaknessLoc)}",
                StyleClasses = { AshfallDossierSheetlet.SerifItalicClass },
                FontColorOverride = Color.FromHex("#7E837E"),
                Margin = new Thickness(0, 2, 0, 0),
            };
            col.AddChild(weaknessLabel);
        }

        row.AddChild(col);
        DossierSections.AddChild(row);
    }

    private void RefreshDossierIdentity()
    {
        var jobName = string.Empty;
        if (_choices.SelectedJob != default && _prototypes.TryIndex(_choices.SelectedJob, out var job))
            jobName = Loc.GetString(job.Name);

        CharacterJobTag.Text = jobName;
        CharacterJobTag.Visible = !string.IsNullOrEmpty(jobName);
        CharacterJobTag.FontColorOverride = GetDomainColor();
    }

    private Color GetDomainColor()
    {
        if (!_prototypes.TryIndex(_choices.Step2Vector, out var step2Opt))
            return AshfallStylesheet.PrimaryAmber;

        return step2Opt.Domain switch
        {
            "Engineering" => Color.FromHex("#D48944"),
            "Medical" => Color.FromHex("#3B82A6"),
            "Security" => Color.FromHex("#B83C3C"),
            "Service" => Color.FromHex("#3FA85B"),
            _ => AshfallStylesheet.PrimaryAmber,
        };
    }

    private static bool IsJobInDomain(JobPrototype job, string domain)
    {
        var id = job.ID.ToLowerInvariant();
        return domain switch
        {
            "Engineering" => id.Contains("engineer") || id.Contains("atmos") || id.Contains("mechanic") || id.Contains("technical"),
            "Medical" => id.Contains("medic") || id.Contains("doctor") || id.Contains("chemist") || id.Contains("paramedic") || id.Contains("virolog"),
            "Security" => id.Contains("security") || id.Contains("officer") || id.Contains("detective") || id.Contains("warden") || id.Contains("cadet"),
            "Service" => id.Contains("janitor") || id.Contains("bartender") || id.Contains("chef") || id.Contains("cook") || id.Contains("botanist") || id.Contains("clown") || id.Contains("mime") || id.Contains("passenger"),
            _ => true,
        };
    }

    private void OnExperienceChanged(OptionButton.ItemSelectedEventArgs args)
    {
        ExperienceOption.SelectId(args.Id);
        _choices.ExperienceTier = args.Id;
    }

    private void OnJobSelected(OptionButton.ItemSelectedEventArgs args)
    {
        JobOption.SelectId(args.Id);
        if (args.Id >= 0 && args.Id < _departmentJobs.Count)
        {
            _choices.SelectedJob = _departmentJobs[args.Id];
            RefreshDossierIdentity();
        }
    }

    private void RerollName()
    {
        if (_currentProfile == null || _currentCulture == null)
            return;

        var firstDataset = _prototypes.Index<DatasetPrototype>(
            _currentProfile.Gender == Gender.Female ? _currentCulture.FirstNamesFemale : _currentCulture.FirstNamesMale);
        var lastDataset = _prototypes.Index<DatasetPrototype>(_currentCulture.LastNames);

        var first = _random.Pick(firstDataset.Values);
        var last = _random.Pick(lastDataset.Values);
        _candidateName = $"{first} {last}";
        CharacterNameLabel.Text = _candidateName;
        _currentProfile = _currentProfile.WithName(_candidateName);
    }

    private void ConfirmCandidate()
    {
        _choices.CustomName = string.IsNullOrWhiteSpace(_candidateName) ? null : _candidateName;
        _choices.TargetSlotIndex = _targetSlot;

        _genSystem.SubmitLifepath(_choices);
        Finished?.Invoke();
    }
}
