using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using Ashfall.Client.Stylesheets;
using Content.Shared.Ashfall.CharacterGen;
using Content.Shared.Ashfall.CharacterGen.Lifepath;
using Content.Shared.Ashfall.CharacterGen.Prototypes;
using Content.Shared.Dataset;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Robust.Shared.Enums;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Timing;

namespace Content.Client.Ashfall.CharacterGen.UI.Lifepath;

public sealed class FloatingContainer : PanelContainer
{
    public Vector2i RenderOffset { get; set; }

    protected override void RenderChildOverride(ref ControlRenderArguments args, int childIndex, Vector2i position)
    {
        RenderControl(ref args, childIndex, position + RenderOffset);
    }
}

public sealed partial class AshfallLifepathScreen : PanelContainer
{
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _prototypes = default!;
    [Dependency] private IRobustRandom _random = default!;
    [Dependency] private IResourceCache _resCache = default!;

    private const int TotalSteps = 5;
    private const string MorphShaderId = "AshfallLifepathMorph";
    private const string HumanSpeciesId = "Human";

    private readonly AshfallCharacterGenSystem _genSystem;
    private readonly AshfallCharacterGenerator _characterGenerator;
    private readonly AshfallPersonGenerator _personGenerator;

    private Button BackButton => this.FindControl<Button>("BackButton");
    private BoxContainer ProgressRail => this.FindControl<BoxContainer>("ProgressRail");
    private Label StepCounterLabel => this.FindControl<Label>("StepCounterLabel");
    private PanelContainer SpriteFrame => this.FindControl<PanelContainer>("SpriteFrame");
    private ProfilePortraitSpriteView PreviewSprite => this.FindControl<ProfilePortraitSpriteView>("PreviewSprite");

    private Label CharacterNameLabel => this.FindControl<Label>("CharacterNameLabel");
    private Button RerollNameButton => this.FindControl<Button>("RerollNameButton");
    private Label CharacterBioLabel => this.FindControl<Label>("CharacterBioLabel");
    private Label CharacterJobTag => this.FindControl<Label>("CharacterJobTag");

    private Label PromptQuestionLabel => this.FindControl<Label>("PromptQuestionLabel");

    private BoxContainer ContentColumn => this.FindControl<BoxContainer>("ContentColumn");
    private BoxContainer OptionsContainer => this.FindControl<BoxContainer>("OptionsContainer");

    private BoxContainer DossierContainer => this.FindControl<BoxContainer>("DossierContainer");
    private BoxContainer DossierSections => this.FindControl<BoxContainer>("DossierSections");
    private OptionButton ExperienceOption => this.FindControl<OptionButton>("ExperienceOption");
    private OptionButton JobOption => this.FindControl<OptionButton>("JobOption");
    private Button ConfirmCandidateButton => this.FindControl<Button>("ConfirmCandidateButton");

    private BoxContainer MainStage => this.FindControl<BoxContainer>("MainStage");

    private int _targetSlot;
    private int _currentStep = 1;
    private AshfallLifepathChoices _choices = new();

    private HumanoidCharacterProfile? _currentProfile;
    private string _candidateName = string.Empty;
    private bool _nameRerolled;
    private Sex _selectedSex = Sex.Male;
    private AshfallCulturePrototype? _currentCulture;
    private AshfallLifepathOptionPrototype? _step1Option;
    private AshfallLifepathOptionPrototype? _step2Option;

    private readonly List<ProtoId<JobPrototype>> _departmentJobs = new();

    private readonly PanelContainer[] _railSegments = new PanelContainer[TotalSteps];

    private float _totalTime;
    private float _stepTime;
    private float _morphTimer;
    private bool _morphFading;
    private const float MorphDuration = 0.85f;

    private sealed record OptionRow(FloatingContainer Wrapper, ContainerButton Button, Label Desc);
    private readonly List<OptionRow> _optionRows = new();

    public event Action? BackToLobby;
    public event Action? Finished;

    public AshfallLifepathScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _genSystem = _entMan.System<AshfallCharacterGenSystem>();
        var naming = _entMan.System<NamingSystem>();
        var marking = IoCManager.Resolve<Content.Shared.Humanoid.Markings.MarkingManager>();

        _characterGenerator = new AshfallCharacterGenerator(_prototypes, marking, naming);
        _personGenerator = new AshfallPersonGenerator(_prototypes, _characterGenerator);

        BackButton.OnPressed += _ => BackToLobby?.Invoke();
        ExperienceOption.OnItemSelected += OnExperienceChanged;
        JobOption.OnItemSelected += OnJobSelected;
        ConfirmCandidateButton.OnPressed += _ => ConfirmCandidate();
        RerollNameButton.OnPressed += _ => RerollCandidateName();

        LayoutContainer.SetAnchorPreset(MainStage, LayoutContainer.LayoutPreset.Wide);
        LayoutContainer.SetAnchorPreset(PreviewSprite, LayoutContainer.LayoutPreset.Wide);

        PreviewSprite.PortraitFraction = 1.0f;
        PreviewSprite.PortraitScale = 1.0f;
        PreviewSprite.VerticalOffset = 10f;

        BuildProgressRail();
    }

    public void Start(int slotIndex)
    {
        _targetSlot = slotIndex;
        _choices = new AshfallLifepathChoices { TargetSlotIndex = slotIndex };
        _currentStep = 1;
        _currentProfile = null;
        _candidateName = string.Empty;
        _nameRerolled = false;
        _step1Option = null;
        _step2Option = null;
        _currentCulture = null;
        _selectedSex = _random.Prob(0.5f) ? Sex.Male : Sex.Female;

        CharacterNameLabel.Text = string.Empty;
        CharacterNameLabel.Visible = false;
        RerollNameButton.Visible = false;
        CharacterBioLabel.Text = string.Empty;
        CharacterBioLabel.Visible = false;
        CharacterJobTag.Text = string.Empty;
        CharacterJobTag.Visible = false;

        if (_prototypes.TryIndex<ShaderPrototype>(MorphShaderId, out var morphProto))
        {
            PreviewSprite.MorphShader = morphProto.InstanceUnique();
        }
        PreviewSprite.IsSilhouette = true;
        PreviewSprite.MorphProgress = 1.0f;
        PreviewSprite.PortraitFraction = 1.0f;
        PreviewSprite.PortraitScale = 1.0f;
        PreviewSprite.VerticalOffset = 10f;
        SpriteFrame.Visible = true;
        LoadPlaceholderSilhouette();

        LoadStep(1);
    }

    private void LoadPlaceholderSilhouette()
    {
        var species = _prototypes.Index<SpeciesPrototype>(HumanSpeciesId);
        ProtoId<CharacterGenConstraintsPrototype> fallbackId = "HumanDefaultConstraints";
        var constraints = _prototypes.Index(fallbackId);
        var gender = _selectedSex == Sex.Female ? Gender.Female : Gender.Male;
        var (appearance, _) = _characterGenerator.GenerateAppearance(constraints, species, _selectedSex, 30, _random, null);
        var dummyProfile = _characterGenerator.BuildProfile("Unknown", species, _selectedSex, gender, 30, appearance, _random);
        PreviewSprite.LoadPreview(dummyProfile, null, showClothes: false);
    }

    private void BuildProgressRail()
    {
        for (var i = 0; i < TotalSteps; i++)
        {
            var segment = new PanelContainer { SetSize = new Vector2(26, 3) };
            segment.PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#232528") };
            ProgressRail.AddChild(segment);
            _railSegments[i] = segment;
        }
    }

    private void UpdateProgressRail()
    {
        for (var i = 0; i < TotalSteps; i++)
        {
            var color = i + 1 < _currentStep
                ? Color.FromHex("#8A5C33")
                : i + 1 == _currentStep
                    ? AshfallStylesheet.PrimaryAmber
                    : Color.FromHex("#232528");
            ((StyleBoxFlat) _railSegments[i].PanelOverride!).BackgroundColor = color;
        }

        StepCounterLabel.Text = Loc.GetString("ashfall-lifepath-step-counter", ("step", _currentStep), ("total", TotalSteps));
    }

    private void LoadStep(int step)
    {
        _currentStep = step;
        UpdateProgressRail();

        PromptQuestionLabel.Text = Loc.GetString($"ashfall-lifepath-prompt-step{step}");
        PromptQuestionLabel.Modulate = new Color(1f, 1f, 1f, 0f);
        _stepTime = 0f;

        if (step <= 4)
        {
            OptionsContainer.Visible = true;
            DossierContainer.Visible = false;
            RerollNameButton.Visible = false;
            PopulateOptions(step);
        }
        else
        {
            OptionsContainer.Visible = false;
            DossierContainer.Visible = true;
            RerollNameButton.Visible = true;
            PopulateDossier();
        }
    }

    private static string WrapText(string text, int maxChars = 54)
    {
        if (text.Length <= maxChars || text.Contains('\n'))
            return text;

        var words = text.Split(' ');
        var sb = new StringBuilder();
        var currentLen = 0;
        foreach (var word in words)
        {
            if (currentLen > 0 && currentLen + word.Length + 1 > maxChars)
            {
                sb.Append('\n');
                currentLen = 0;
            }
            else if (currentLen > 0)
            {
                sb.Append(' ');
                currentLen++;
            }
            sb.Append(word);
            currentLen += word.Length;
        }
        return sb.ToString();
    }

    private static float EaseInOutCubic(float t)
    {
        return t < 0.5f ? 4f * t * t * t : 1f - MathF.Pow(-2f * t + 2f, 3f) / 2f;
    }

    private void PopulateOptions(int step)
    {
        OptionsContainer.RemoveAllChildren();
        _optionRows.Clear();

        var allStepOptions = _prototypes.EnumeratePrototypes<AshfallLifepathOptionPrototype>()
            .Where(o => o.Step == step)
            .ToList();

        List<AshfallLifepathOptionPrototype> options;

        if (step == 1)
        {
            // Step 1: Draw 4 distinct origins from the master pool of 24+ origins
            _random.Shuffle(allStepOptions);
            options = allStepOptions.Take(4).ToList();
        }
        else if (step == 2 && _step1Option != null)
        {
            // Step 2: Causal filtering based on Step 1 origin tags
            var originTags = _step1Option.Tags;
            var matching = allStepOptions.Where(o => o.MatchingTags.Any(t => originTags.Contains(t))).ToList();
            var fallback = allStepOptions.Except(matching).ToList();

            _random.Shuffle(matching);
            _random.Shuffle(fallback);

            options = matching.Concat(fallback).Take(4).ToList();
            _random.Shuffle(options);
        }
        else if (step == 3)
        {
            // Step 3: Bias traits contextually by craft domain or origin tags
            var domain = _step2Option?.Domain;
            var originTags = _step1Option?.Tags ?? new List<string>();

            var matching = allStepOptions.Where(o =>
                (!string.IsNullOrEmpty(domain) && o.Domain == domain) ||
                o.MatchingTags.Any(t => originTags.Contains(t))).ToList();
            var fallback = allStepOptions.Except(matching).ToList();

            _random.Shuffle(matching);
            _random.Shuffle(fallback);

            options = matching.Concat(fallback).Take(4).ToList();
            _random.Shuffle(options);
        }
        else if (step == 4)
        {
            // Step 4: Bias motivations contextually by prior choices
            var originTags = _step1Option?.Tags ?? new List<string>();
            var craftTags = _step2Option?.Tags ?? new List<string>();

            var matching = allStepOptions.Where(o =>
                o.MatchingTags.Any(t => originTags.Contains(t) || craftTags.Contains(t))).ToList();
            var fallback = allStepOptions.Except(matching).ToList();

            _random.Shuffle(matching);
            _random.Shuffle(fallback);

            options = matching.Concat(fallback).Take(4).ToList();
            _random.Shuffle(options);
        }
        else
        {
            _random.Shuffle(allStepOptions);
            options = allStepOptions.Take(4).ToList();
        }

        for (var i = 0; i < options.Count; i++)
        {
            var row = CreateOptionRow(i + 1, options[i]);
            row.Button.Modulate = new Color(1f, 1f, 1f, 0f);
            _optionRows.Add(row);
            OptionsContainer.AddChild(row.Wrapper);
        }
    }

    private OptionRow CreateOptionRow(int index, AshfallLifepathOptionPrototype opt)
    {
        var wrapper = new FloatingContainer
        {
            HorizontalExpand = true,
        };

        var button = new ContainerButton
        {
            StyleClasses = { ContainerButton.StyleClassButton, AshfallDossierSheetlet.OptionCardClass },
            HorizontalExpand = true,
        };

        var wrapped = WrapText(Loc.GetString(opt.Description), 54);

        var descLabel = new Label
        {
            Text = wrapped,
            StyleClasses = { AshfallDossierSheetlet.SerifClass },
            HorizontalExpand = true,
        };

        button.AddChild(descLabel);
        wrapper.AddChild(button);

        var captured = opt;
        button.OnPressed += _ => SelectOption(captured);

        return new OptionRow(wrapper, button, descLabel);
    }

    private void SelectOption(AshfallLifepathOptionPrototype opt)
    {
        switch (opt.Step)
        {
            case 1:
                _choices.Step1Origin = opt.ID;
                UpdateSpriteStep1(opt);
                LoadStep(2);
                break;

            case 2:
                _choices.Step2Vector = opt.ID;
                UpdateSpriteStep2(opt);
                LoadStep(3);
                break;

            case 3:
                _choices.Step3Flaw = opt.ID;
                LoadStep(4);
                break;

            case 4:
                _choices.Step4Luggage = opt.ID;
                LoadStep(5);
                break;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _totalTime += (float) args.DeltaSeconds;
        _stepTime += (float) args.DeltaSeconds;

        // Character morph shader animation
        if (_morphFading)
        {
            _morphTimer += (float) args.DeltaSeconds;
            var morphT = Math.Clamp(_morphTimer / MorphDuration, 0f, 1f);
            var easedMorph = EaseInOutCubic(morphT);
            PreviewSprite.MorphProgress = easedMorph;
            CharacterNameLabel.Modulate = new Color(1f, 1f, 1f, easedMorph);
            CharacterBioLabel.Modulate = new Color(1f, 1f, 1f, easedMorph);

            if (morphT >= 1f)
            {
                _morphFading = false;
                PreviewSprite.MorphProgress = 1.0f;
                CharacterNameLabel.Modulate = Color.White;
                CharacterBioLabel.Modulate = Color.White;
            }
        }
        PreviewSprite.MorphTime = _totalTime;

        // Step question fade in from dark
        var qProgress = Math.Clamp(_stepTime / 0.4f, 0f, 1f);
        PromptQuestionLabel.Modulate = new Color(1f, 1f, 1f, EaseInOutCubic(qProgress));

        // Option rows staggered cascade fade in + organic floating motion
        const float answersDelay = 0.22f;
        const float answerInterval = 0.12f;
        const float answerFadeDuration = 0.35f;

        for (var i = 0; i < _optionRows.Count; i++)
        {
            var row = _optionRows[i];
            var cardDelay = answersDelay + i * answerInterval;
            if (_stepTime >= cardDelay)
            {
                var prog = Math.Clamp((_stepTime - cardDelay) / answerFadeDuration, 0f, 1f);
                row.Button.Modulate = new Color(1f, 1f, 1f, EaseInOutCubic(prog));
            }
            else
            {
                row.Button.Modulate = new Color(1f, 1f, 1f, 0f);
            }

            // Independent subtle organic floating drift
            var dx = (int)(MathF.Sin(_totalTime * 1.3f + i * 1.7f) * 2.5f);
            var dy = (int)(MathF.Cos(_totalTime * 1.0f + i * 1.3f) * 1.5f);
            row.Wrapper.RenderOffset = new Vector2i(dx, dy);
        }

    }

    private void RerollCandidateName()
    {
        if (_currentProfile == null)
            return;

        var gender = _selectedSex == Sex.Female ? Gender.Female : Gender.Male;
        var newName = _currentCulture != null
            ? _random.Pick(_prototypes.Index<DatasetPrototype>(gender == Gender.Female ? _currentCulture.FirstNamesFemale : _currentCulture.FirstNamesMale).Values) + " " +
              _random.Pick(_prototypes.Index<DatasetPrototype>(_currentCulture.LastNames).Values)
            : Loc.GetString("ashfall-lifepath-default-candidate-name");

        _candidateName = newName;
        _currentProfile = _currentProfile.WithName(newName);
        CharacterNameLabel.Text = _candidateName;
        _nameRerolled = true;
    }

    private void RegenerateCandidateIdentity()
    {
        if (_step1Option == null)
            return;

        var speciesId = _step1Option.Species ?? "Human";
        var species = _prototypes.Index(speciesId);

        CharacterGenConstraintsPrototype constraints;
        if (_prototypes.TryIndex<CharacterGenConstraintsPrototype>($"{species.ID}DefaultConstraints", out var found))
            constraints = found;
        else
        {
            ProtoId<CharacterGenConstraintsPrototype> fallbackId = "HumanDefaultConstraints";
            constraints = _prototypes.Index(fallbackId);
        }

        var gender = _selectedSex switch
        {
            Sex.Female => Gender.Female,
            Sex.Male => Gender.Male,
            _ => Gender.Epicene
        };

        var age = 30;
        var (appearance, _) = _characterGenerator.GenerateAppearance(constraints, species, _selectedSex, age, _random, _currentCulture);
        var name = _currentCulture != null
            ? _random.Pick(_prototypes.Index<DatasetPrototype>(gender == Gender.Female ? _currentCulture.FirstNamesFemale : _currentCulture.FirstNamesMale).Values) + " " +
              _random.Pick(_prototypes.Index<DatasetPrototype>(_currentCulture.LastNames).Values)
            : Loc.GetString("ashfall-lifepath-default-candidate-name");

        _currentProfile = _characterGenerator.BuildProfile(name, species, _selectedSex, gender, age, appearance, _random);
        _candidateName = name;
        _nameRerolled = false;
        CharacterNameLabel.Text = _candidateName;

        var speciesName = _prototypes.TryIndex<SpeciesPrototype>(_currentProfile.Species, out var sp)
            ? Loc.GetString(sp.Name)
            : string.Empty;
        var cultureName = _currentCulture != null ? Loc.GetString(_currentCulture.Label) : string.Empty;
        CharacterBioLabel.Text = string.IsNullOrEmpty(cultureName) ? speciesName : $"{speciesName} • {cultureName}";

        if (_step2Option != null && _step2Option.PreviewJob is { } jobId && _prototypes.TryIndex(jobId, out JobPrototype? job))
            PreviewSprite.LoadPreview(_currentProfile, job, showClothes: true);
        else
            PreviewSprite.LoadPreview(_currentProfile, null, showClothes: false);
    }

    private void UpdateSpriteStep1(AshfallLifepathOptionPrototype opt)
    {
        _step1Option = opt;
        if (opt.Culture is { } cId && _prototypes.TryIndex(cId, out var cult))
            _currentCulture = cult;
        else
            _currentCulture = null;

        RegenerateCandidateIdentity();
        PreviewSprite.IsSilhouette = false;
        PreviewSprite.MorphProgress = 0f;
        _morphTimer = 0f;
        _morphFading = true;
        CharacterNameLabel.Visible = true;
        CharacterBioLabel.Visible = true;
        CharacterNameLabel.Modulate = new Color(1f, 1f, 1f, 0f);
        CharacterBioLabel.Modulate = new Color(1f, 1f, 1f, 0f);
    }

    private void UpdateSpriteStep2(AshfallLifepathOptionPrototype opt)
    {
        _step2Option = opt;
        if (_currentProfile == null)
            return;

        if (opt.PreviewJob is { } jobId && _prototypes.TryIndex(jobId, out JobPrototype? job))
        {
            PreviewSprite.LoadPreview(_currentProfile, job, showClothes: true);
            PreviewSprite.MorphProgress = 0f;
            _morphTimer = 0f;
            _morphFading = true;
        }
    }

    private void PopulateDossier()
    {
        ConfirmCandidateButton.Text = Loc.GetString("ashfall-lifepath-confirm-button", ("slot", _targetSlot + 1));
        DossierSections.RemoveAllChildren();

        // 1. Origin & Craft summary
        if (_step1Option != null && _step2Option != null)
        {
            var originCraft = CreateSummaryRow(
                "ashfall-lifepath-header-step1",
                $"{Loc.GetString(_step1Option.Title)}  •  {Loc.GetString(_step2Option.Title)}",
                null,
                null);
            DossierSections.AddChild(originCraft);
        }

        // 2. Character Flaw & Stress Weakness
        if (_prototypes.TryIndex(_choices.Step3Flaw, out var flawOpt))
        {
            var weakness = flawOpt.StressWeaknessLoc is { } wLoc ? Loc.GetString(wLoc) : null;
            var flawRow = CreateSummaryRow(
                "ashfall-lifepath-ledger-flaw",
                Loc.GetString(flawOpt.Title),
                weakness != null ? $"{Loc.GetString("ashfall-lifepath-flaw-weakness")}: {weakness}" : null,
                null);
            DossierSections.AddChild(flawRow);
        }

        // 3. Motivation quote
        if (_prototypes.TryIndex(_choices.Step4Luggage, out var lugOpt))
        {
            var motRow = CreateSummaryRow(
                "ashfall-lifepath-ledger-luggage",
                Loc.GetString(lugOpt.Title),
                null,
                Loc.GetString(lugOpt.Description));
            DossierSections.AddChild(motRow);
        }

        // Experience tiers
        ExperienceOption.Clear();
        ExperienceOption.AddItem(Loc.GetString("ashfall-lifepath-exp-junior"), 0);
        ExperienceOption.AddItem(Loc.GetString("ashfall-lifepath-exp-standard"), 1);
        ExperienceOption.AddItem(Loc.GetString("ashfall-lifepath-exp-veteran"), 2);
        ExperienceOption.SelectId(_choices.ExperienceTier);

        // Populate jobs strictly from the chosen domain
        _prototypes.TryIndex(_choices.Step2Vector, out var step2Opt);
        var domain = step2Opt?.Domain ?? "Engineering";

        _departmentJobs.Clear();
        JobOption.Clear();

        var matchingJobs = GetJobsForDomain(domain);
        if (matchingJobs.Count == 0 && step2Opt?.PreviewJob is { } prevJob && _prototypes.TryIndex(prevJob, out JobPrototype? pj))
        {
            matchingJobs.Add(pj);
        }

        for (var i = 0; i < matchingJobs.Count; i++)
        {
            var job = matchingJobs[i];
            _departmentJobs.Add(job.ID);
            JobOption.AddItem(Loc.GetString(job.Name), i);
        }

        if (_departmentJobs.Count > 0)
        {
            JobOption.SelectId(0);
            _choices.SelectedJob = _departmentJobs[0];
            if (_currentProfile != null && _prototypes.TryIndex(_choices.SelectedJob, out JobPrototype? jobProto))
            {
                PreviewSprite.LoadPreview(_currentProfile, jobProto, showClothes: true);
            }
        }

        RefreshDossierIdentity();
    }

    private Control CreateSummaryRow(string headerKey, string mainText, string? subBadge, string? quote)
    {
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            SeparationOverride = 3,
            HorizontalExpand = true,
        };

        var label = new Label
        {
            Text = Loc.GetString(headerKey),
            StyleClasses = { AshfallDossierSheetlet.LedgerStepClass },
        };
        box.AddChild(label);

        var contentRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 8,
            HorizontalExpand = true,
        };

        var mainLabel = new Label
        {
            Text = mainText,
            StyleClasses = { AshfallDossierSheetlet.OptionTitleClass },
        };
        contentRow.AddChild(mainLabel);

        if (subBadge != null)
        {
            var badgeLabel = new Label
            {
                Text = subBadge,
                StyleClasses = { AshfallDossierSheetlet.WeaknessClass },
                VAlign = Label.VAlignMode.Center,
            };
            contentRow.AddChild(badgeLabel);
        }

        box.AddChild(contentRow);

        if (quote != null)
        {
            var quoteLabel = new Label
            {
                Text = WrapText(quote, 54),
                StyleClasses = { AshfallDossierSheetlet.SerifItalicClass },
                Margin = new Thickness(0, 2, 0, 0),
            };
            box.AddChild(quoteLabel);
        }

        return box;
    }

    private void RefreshDossierIdentity()
    {
        var jobName = string.Empty;
        if (_choices.SelectedJob != default && _prototypes.TryIndex(_choices.SelectedJob, out var job))
            jobName = Loc.GetString(job.Name);

        CharacterJobTag.Text = jobName;
        CharacterJobTag.Visible = !string.IsNullOrEmpty(jobName);
        CharacterJobTag.FontColorOverride = GetDomainColor();
    }

    private Color GetDomainColor()
    {
        if (!_prototypes.TryIndex(_choices.Step2Vector, out var step2Opt))
            return Color.FromHex("#C88A3E");

        return step2Opt.Domain switch
        {
            "Engineering" => Color.FromHex("#D48944"),
            "Medical" => Color.FromHex("#4892B0"),
            "Security" => Color.FromHex("#A8564E"),
            "Service" => Color.FromHex("#4E9B65"),
            _ => Color.FromHex("#C88A3E"),
        };
    }

    private List<JobPrototype> GetJobsForDomain(string domain)
    {
        var result = new List<JobPrototype>();
        if (_prototypes.TryIndex<DepartmentPrototype>(domain, out var dept))
        {
            foreach (var roleId in dept.Roles)
            {
                if (_prototypes.TryIndex(roleId, out var job) && job.SetPreference)
                {
                    if (!roleId.Id.StartsWith("Chief") && !roleId.Id.StartsWith("Head") &&
                        roleId.Id != "Captain" && roleId.Id != "Quartermaster" && roleId.Id != "ResearchDirector")
                    {
                        result.Add(job);
                    }
                }
            }
        }

        if (result.Count == 0)
        {
            result = _prototypes.EnumeratePrototypes<JobPrototype>()
                .Where(j => j.SetPreference && IsJobInDomain(j, domain))
                .ToList();
        }

        return result;
    }

    private static bool IsJobInDomain(JobPrototype job, string domain)
    {
        var id = job.ID.ToLowerInvariant();
        return domain switch
        {
            "Engineering" => id.Contains("engineer") || id.Contains("atmos") || id.Contains("mechanic") || id.Contains("technical"),
            "Medical" => id.Contains("medic") || id.Contains("doctor") || id.Contains("chemist") || id.Contains("paramedic") || id.Contains("virolog"),
            "Security" => id.Contains("security") || id.Contains("officer") || id.Contains("detective") || id.Contains("warden") || id.Contains("cadet"),
            "Service" => id.Contains("janitor") || id.Contains("bartender") || id.Contains("chef") || id.Contains("cook") || id.Contains("botanist") || id.Contains("clown") || id.Contains("mime") || id.Contains("passenger"),
            _ => true,
        };
    }

    private void OnExperienceChanged(OptionButton.ItemSelectedEventArgs args)
    {
        ExperienceOption.SelectId(args.Id);
        _choices.ExperienceTier = args.Id;
        if (_currentProfile != null)
        {
            var newAge = args.Id switch
            {
                0 => _random.Next(19, 25),
                2 => _random.Next(44, 60),
                _ => _random.Next(27, 40),
            };
            _currentProfile = _currentProfile.WithAge(newAge);
        }
    }

    private void OnJobSelected(OptionButton.ItemSelectedEventArgs args)
    {
        JobOption.SelectId(args.Id);
        if (args.Id >= 0 && args.Id < _departmentJobs.Count)
        {
            _choices.SelectedJob = _departmentJobs[args.Id];
            if (_currentProfile != null && _prototypes.TryIndex(_choices.SelectedJob, out JobPrototype? jobProto))
            {
                PreviewSprite.LoadPreview(_currentProfile, jobProto, showClothes: true);
            }
            RefreshDossierIdentity();
        }
    }

    private void ConfirmCandidate()
    {
        // A generated preview name stays display-only so the server can roll its own culture name.
        _choices.CustomName = _nameRerolled && !string.IsNullOrWhiteSpace(_candidateName) ? _candidateName : null;
        _choices.TargetSlotIndex = _targetSlot;
        // Identity is rebuilt server-side; only the preview's sex roll is preserved.
        _choices.SelectedSex = _selectedSex;

        _genSystem.SubmitLifepath(_choices);
        Finished?.Invoke();
    }
}
