using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client.Ashfall.CharacterGen.UI.Lifepath;

public sealed partial class AshfallLobbySlotsScreen : PanelContainer
{
    [Dependency] private IEntityManager _entMan = default!;

    private readonly AshfallCharacterGenSystem _genSystem;

    private Button BackButton => this.FindControl<Button>("BackButton");
    private BoxContainer SlotsContainer => this.FindControl<BoxContainer>("SlotsContainer");
    private AshfallLobbySlotCard Slot0 => this.FindControl<AshfallLobbySlotCard>("Slot0");
    private AshfallLobbySlotCard Slot1 => this.FindControl<AshfallLobbySlotCard>("Slot1");
    private AshfallLobbySlotCard Slot2 => this.FindControl<AshfallLobbySlotCard>("Slot2");

    private readonly AshfallLobbySlotCard[] _cards;

    private bool _isZooming;
    private float _zoomProgress;
    private int _targetSlot;

    public event Action? BackToLobby;
    public event Action<int>? StartLifepathRequested;

    public AshfallLobbySlotsScreen()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _genSystem = _entMan.System<AshfallCharacterGenSystem>();
        _cards = new[] { Slot0, Slot1, Slot2 };

        BackButton.OnPressed += _ => BackToLobby?.Invoke();

        for (var i = 0; i < _cards.Length; i++)
        {
            var idx = i;
            _cards[i].SlotClicked += slot => OnSlotClicked(slot);
            _cards[i].SelectPressed += slot => _genSystem.SelectSlot(slot);
            _cards[i].ResetPressed += slot => _genSystem.ResetSlot(slot);
        }

        _genSystem.PoolUpdated += UpdateSlots;
        UpdateSlots();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _genSystem.RequestPool(refresh: false);
        UpdateSlots();
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        if (disposing)
        {
            _genSystem.PoolUpdated -= UpdateSlots;
        }
    }

    public void UpdateSlots()
    {
        var confirmed = _genSystem.ConfirmedSlotIndex;

        for (var i = 0; i < _cards.Length; i++)
        {
            var slotDto = _genSystem.GetPinnedSlot(i);
            var isSelected = (confirmed == i) || (confirmed < 0 && i == 0 && slotDto != null);
            _cards[i].SetSlot(i, slotDto, isSelected);
        }
    }

    private void OnSlotClicked(int slotIndex)
    {
        _targetSlot = slotIndex;
        _isZooming = true;
        _zoomProgress = 0f;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_isZooming)
            return;

        _zoomProgress += args.DeltaSeconds * 3.5f;

        // Smooth zoom effect: scale clicked slot while fading others
        var factor = Math.Clamp(_zoomProgress, 0f, 1f);
        var scale = 1f + factor * 0.15f;

        for (var i = 0; i < _cards.Length; i++)
        {
            if (i == _targetSlot)
            {
                _cards[i].Modulate = Color.White;
            }
            else
            {
                var fade = MathHelper.Lerp(1f, 0f, factor);
                _cards[i].Modulate = new Color(1f, 1f, 1f, fade);
            }
        }

        if (_zoomProgress >= 1f)
        {
            _isZooming = false;
            // Reset opacity for return
            for (var i = 0; i < _cards.Length; i++)
            {
                _cards[i].Modulate = Color.White;
            }

            StartLifepathRequested?.Invoke(_targetSlot);
        }
    }
}
